from models import db, Book, User
from app import app
from werkzeug.security import generate_password_hash

FAVORITES = [
    {
        "title": "Мастер и Маргарита",
        "author": "М. Булгаков",
        "year": 1967,
        "category": "Роман",
        "description": "Один из главных романов XX века. Сатирическая фантазия о Москве и вечных вопросах.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/282202.webp",
        "price_buy": 599, "price_rent_2w": 159, "price_rent_1m": 279, "price_rent_3m": 469,
        "status": "Новинка", "available": True,
    },
    {
        "title": "1984",
        "author": "Дж. Оруэлл",
        "year": 1949,
        "category": "Антиутопия",
        "description": "Классика антиутопии о тотальном контроле и языке, который меняет реальность.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/6130253.webp",
        "price_buy": 499, "price_rent_2w": 149, "price_rent_1m": 249, "price_rent_3m": 449,
        "status": "Активна", "available": True,
    },
    {
        "title": "Пикник на обочине",
        "author": "А. и Б. Стругацкие",
        "year": 1972,
        "category": "Фантастика",
        "description": "Легендарная фантастика о Зоне и артефактах, которые меняют людей.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/127607.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Sapiens: Краткая история человечества",
        "author": "Ю. Н. Харари",
        "year": 2011,
        "category": "Нон-фикшн",
        "description": "Как Homo sapiens стал доминирующим видом и почему это важно сегодня.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/70441858.webp",
        "price_buy": 799, "price_rent_2w": 199, "price_rent_1m": 349, "price_rent_3m": 599,
        "status": "Активна", "available": True,
    },
    {
        "title": "Другая история Золушки. Стая. Книга 1",
        "author": "Софи Ларк",
        "year": 2026,
        "category": "Роман",
        "description": "Темная романтическая история с опасными правилами и выбором, который меняет жизнь. Первая книга цикла «Стая».",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/73111938.webp",
        "price_buy": 999, "price_rent_2w": 259, "price_rent_1m": 379, "price_rent_3m": 569,
        "status": "Новинка", "available": True,
    },
    {
        "title": "Железное пламя",
        "author": "Ребекка Яррос",
        "year": 2024,
        "category": "Фэнтези",
        "description": "Продолжение драконьей саги: больше испытаний, интриг и решений на грани. Цена силы становится выше.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/70595056.webp",
        "price_buy": 599, "price_rent_2w": 159, "price_rent_1m": 279, "price_rent_3m": 469,
        "status": "Новинка", "available": True,
    },
    {
        "title": "Грозовой перевал",
        "author": "Эмили Бронте",
        "year": 1847,
        "category": "Классика",
        "description": "Классический роман о страсти, гордости и разрушительной любви. Атмосфера суровых вересковых пустошей.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/5629614.webp",
        "price_buy": 599, "price_rent_2w": 159, "price_rent_1m": 279, "price_rent_3m": 469,
        "status": "Новинка", "available": True,
    },
    {
        "title": "Четвертое крыло",
        "author": "Ребекка Яррос",
        "year": 2023,
        "category": "Фэнтези",
        "description": "Учеба в военной академии, где выживает не каждый. Драконы, испытания и борьба за место среди сильнейших.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/69747151.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Дочь предателя. Баллада Пепла и Льда. Книга 1",
        "author": "Сорен Свейструп",
        "year": 2025,
        "category": "Фэнтези",
        "description": "Фэнтези с политическими интригами, семейными тайнами и холодной решимостью героини. Начало цикла.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/72060061.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Граф Аверин. Колдун Российской империи",
        "author": "Виктор Дашкевич",
        "year": 2024,
        "category": "Фэнтези",
        "description": "Альтернативная история с магией и имперским размахом. Колдун и интриги — на фоне большой эпохи.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/69526501.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Тревожные люди",
        "author": "Фредрик Бакман",
        "year": 2019,
        "category": "Современная проза",
        "description": "Трогательная история о людях, которые очень стараются быть сильными. Смешно, тепло и по-человечески.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/63028197.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Преследуя Аделин",
        "author": "Х. Д. Карлтон",
        "year": 2021,
        "category": "Роман",
        "description": "Темный роман с напряжением, играми власти и эмоциональными границами. История на грани.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/70530550.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Дизайнер Жорка. Книга 1",
        "author": "Анна Шаенская",
        "year": 2025,
        "category": "Юмор",
        "description": "Легкая и забавная история с характером. Начало приключений харизматичного героя.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/71199073.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Ты попала, ведьма!",
        "author": "Анна Пожарская",
        "year": 2026,
        "category": "Фэнтези",
        "description": "Ироничное фэнтези про внезапные способности, магический хаос и последствия случайных заклинаний.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/73079138.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Академия Астра. Обручённые судьбой",
        "author": "Лана Лей",
        "year": 2026,
        "category": "Фэнтези",
        "description": "Академия, тайные правила и «связь судьбы», от которой не спрятаться. Романтика и магия в одном.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/73180208.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Фаталити. Цена его успеха",
        "author": "Дана Делон",
        "year": 2023,
        "category": "Роман",
        "description": "История о том, как успех меняет людей и отношения. Личные решения важнее красивой картинки.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/69466855.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Завет воды",
        "author": "Абрахам Вергезе",
        "year": 2023,
        "category": "Современная проза",
        "description": "Большая семейная сага, тайны поколений и глубокая человеческая драма на фоне исторических перемен.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/70795744.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Ген Рафаила",
        "author": "Евгения Михайлова",
        "year": 2024,
        "category": "Детектив",
        "description": "Детектив с личной драмой и расследованием, где прошлое возвращается неожиданными деталями.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/70479511.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Охотясь на Аделин",
        "author": "Х. Д. Карлтон",
        "year": 2021,
        "category": "Роман",
        "description": "Продолжение темной истории: напряжение растет, ставки выше, а границы чувств — тоньше.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/71008186.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Счастливый карман, полный денег",
        "author": "Дэвид Кэмерон Джиканди",
        "year": 2007,
        "category": "Саморазвитие",
        "description": "Книга о мышлении, ценностях и привычках, которые помогают иначе смотреть на деньги и возможности.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/63841423.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Дневники. Я могу объяснить многое",
        "author": "Никола Тесла",
        "year": 2017,
        "category": "Биографии",
        "description": "Воспоминания и размышления Теслы: идеи, которые опередили время, и взгляд изнутри на путь изобретателя.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/24434720.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Атомные привычки",
        "author": "Джеймс Клир",
        "year": 2018,
        "category": "Саморазвитие",
        "description": "Про маленькие ежедневные изменения, которые дают большой результат. Система привычек вместо мотивации.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/48514275.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Трансерфинг реальности. Ступень I: Пространство вариантов",
        "author": "Вадим Зеланд",
        "year": 2007,
        "category": "Саморазвитие",
        "description": "Практики и идеи про выбор сценариев жизни и управление вниманием. Книга-«классика» жанра.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/140682.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Самый богатый человек в Вавилоне",
        "author": "Джордж Сэмюэль Клейсон",
        "year": 1926,
        "category": "Финансы",
        "description": "Финансовые принципы в формате притч: откладывать, инвестировать и жить по средствам — без скучной теории.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/23593618.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Свобода от тревоги. Справься с тревогой, пока она не расправилась с тобой",
        "author": "Роберт Лихи",
        "year": 2009,
        "category": "Психология",
        "description": "Пошаговые техники КПТ: как снижать тревогу и перестать жить в режиме ожидания плохого.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/65801305.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Как завоевывать друзей и оказывать влияние на людей",
        "author": "Дейл Карнеги",
        "year": 1981,
        "category": "Коммуникации",
        "description": "Классика общения: как договариваться, располагать к себе и строить отношения без конфликтов.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/14141955.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Думай медленно… Решай быстро",
        "author": "Даниэль Канеман",
        "year": 2011,
        "category": "Психология",
        "description": "Про два режима мышления и когнитивные ошибки. Помогает принимать решения спокойнее и точнее.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/6444517.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "Психология влияния. 7-е расширенное издание",
        "author": "Роберт Чалдини",
        "year": 2021,
        "category": "Психология",
        "description": "Почему мы говорим «да» и как работают принципы убеждения. Полезно для общения и самозащиты от манипуляций.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/6994167.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "НИ СЫ. Будь уверен в своих силах и не позволяй сомнениям мешать тебе двигаться вперед",
        "author": "Джен Синсеро",
        "year": 2013,
        "category": "Саморазвитие",
        "description": "Про уверенность и действия без бесконечных сомнений. Энергичная подача и практичные установки.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/28544335.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "К себе нежно. Книга о том, как ценить и беречь себя",
        "author": "Ольга Примаченко",
        "year": 2020,
        "category": "Саморазвитие",
        "description": "Мягкая книга о заботе о себе, границах и поддержке. Подходит, когда хочется бережного перезапуска.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/62780292.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
    {
        "title": "48 законов власти",
        "author": "Роберт Грин",
        "year": 2011,
        "category": "Саморазвитие",
        "description": "Сборник наблюдений о влиянии, стратегии и поведении в конкурентной среде. Книга-дискуссия.",
        "cover_url": "https://cdn.litres.ru/pub/c/cover_415/134232.webp",
        "price_buy": 549, "price_rent_2w": 159, "price_rent_1m": 269, "price_rent_3m": 459,
        "status": "Активна", "available": True,
    },
]

def main():
    with app.app_context():
        db.create_all()

        # admin по умолчанию
        if not User.query.filter_by(username="admin").first():
            admin = User(username="admin", password=generate_password_hash("admin"), is_admin=True)
            db.session.add(admin)

        # книги
        if Book.query.count() == 0:
            for b in FAVORITES:
                db.session.add(Book(**b))

        db.session.commit()
        print("Seed done. Admin login: admin / admin")

if __name__ == "__main__":
    main()